// build.mjs — 按 manifest 拼接 core/platform/entry 片段为各平台单文件脚本
// 无依赖无转译: 纯文本拼接。产 dist/ 即发布物 (已提交 git, raw URL 指向 dist)。
// 用法: node build.mjs          重生成全部 dist
//       node build.mjs --check  CI 用: 产物有漂移则退出码 1

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));

const CORE_WLOC = ["core/common.js", "core/protobuf.js", "core/wloc-patch.js"];
const CORE_SETTINGS = ["core/common.js", "core/gcj.js", "core/settings.js"];

const MANIFEST = {
  "dist/qx/wloc.js": [...CORE_WLOC, "platform/qx.js", "entry/wloc.js"],
  "dist/qx/wloc-settings.js": [...CORE_SETTINGS, "platform/qx.js", "entry/settings.js"],
  "dist/surge/wloc.js": [...CORE_WLOC, "platform/surge.js", "entry/wloc.js"],
  "dist/surge/wloc-settings.js": [...CORE_SETTINGS, "platform/surge.js", "entry/settings.js"],
};

const banner = (out, parts) =>
  `/* ${path.relative(root, out)} — GENERATED by build.mjs, do not edit.\n` +
  ` * 源文件 (按序): ${parts.join(", ")}\n` +
  ` * 改动请编辑源文件后运行: node build.mjs\n */\n\n`;

// 返回 { 相对路径: 拼接后内容 }
export function build() {
  const files = {};
  for (const [out, parts] of Object.entries(MANIFEST)) {
    const chunks = parts.map((p) => fs.readFileSync(path.join(root, p), "utf8"));
    files[out] = banner(out, parts) + chunks.join("\n");
  }
  return files;
}

function main() {
  const files = build();
  for (const [out, content] of Object.entries(files)) {
    const abs = path.join(root, out);
    const changed = !fs.existsSync(abs) || fs.readFileSync(abs, "utf8") !== content;
    if (process.argv[2] === "--check") {
      if (changed) {
        console.error(`DRIFT: ${out} 与源文件不同步, 请运行 node build.mjs`);
        process.exit(1);
      }
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`${changed ? "updated" : "ok"}  ${out}`);
    }
  }
  if (process.argv[2] === "--check") console.log("check ok: dist 与源文件同步");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
