name: test
on: [push, pull_request]
jobs:
  node-selfcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node build.mjs --check
      - run: node test/demo.mjs
